services:
  - type: web
    name: walmart-airflow-demo
    runtime: docker
    plan: free
    rootDir: airflow_dbt_project
    dockerfilePath: ./Dockerfile

    envVars:
      - key: AIRFLOW__CORE__LOAD_EXAMPLES
        value: "false"

      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor

      - key: AIRFLOW__API__HOST
        value: "0.0.0.0"

      - key: AIRFLOW__API__PORT
        value: "10000"