FROM apache/airflow:3.2.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY dags /opt/airflow/dags
COPY walmart_project /opt/airflow/walmart_project

CMD ["standalone"]