FROM apache/airflow:3.2.0

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends gcc \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

COPY dags /opt/airflow/dags
COPY walmart_project /opt/airflow/walmart_project
COPY start_render.sh /opt/airflow/start_render.sh

RUN airflow db migrate

USER root
RUN chmod +x /opt/airflow/start_render.sh
USER airflow

ENTRYPOINT []
CMD ["/bin/bash", "/opt/airflow/start_render.sh"]