sources:
  - name: walmart_databricks
    database: walmart_db
    schema: public
    tables:
      - name: orders
      - name: customers
      - name: products
      - name: order_items
      - name: stores
      - name: employees